############################################################################################
# Exchange Adapter YAML config.
#
# - Sample config below currently set to run against a totally stubbed exchange which
#   is based on TA4J for backtesting a given strategy
# - All fields are mandatory unless stated otherwise.
# - BX-bot only supports running 1 exchange per bot.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# See the README "How do I write my own Exchange Adapter?" section for more details.
############################################################################################
---
exchange:

  # A friendly name for the Exchange. Value must be an alphanumeric string. Spaces are allowed.
  name: trymode

  # For the adapter value, you must specify the fully qualified name of your Exchange Adapter class so the Trading Engine
  # can load and execute it. The class must be on the runtime classpath.
  adapter: com.gazbert.bxbot.exchanges.TryModeExchangeAdapter

  otherConfig:
    # Exchange Order fee in % for the given market. It counts for sell as well as for buy orders in the simulation
    order-fee: 0.26

    # the counter currency which is simulated. This must fit to your used markets counter currency
    simulatedCounterCurrency: ZEUR

    # the starting balance for the simulation. The simulation starts with this amount as counter currency and 0 as base currency
    counterCurrencyStartingBalance: 100

    # the base currency which is simulated. This must fit to your used markets base currency
    simulatedBaseCurrency: XXRP

    # the starting balance for the simulation. The simulation starts with this amount as base currency
    baseCurrencyStartingBalance: 0

    # the adapter which should be used for public API calls. All special config values for this adapter must be given in this other config section as well
    delegateAdapter: com.gazbert.bxbot.exchanges.KrakenExchangeAdapter

