############################################################################################
# Market YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# NOTE: XXBT is the same currency code as BTC for Bitcoin on Kraken exchange.
############################################################################################
---
markets:
  # The id value is the market id as defined on the exchange, e.g. 'XBTUSD'.
  # Kraken markets assets (e.g. currencies) can be referenced using their ISO4217-A3 names in the case of ISO
  # registered names, their 3 letter commonly used names in the case of unregistered names,
  # or their X-ISO4217-A3 code (see http://www.ifex-project.org/).
  #
  # The Kraken Exchange Adapter expects the market id to use the 3 letter commonly used names,
  # e.g. you access the XBT/USD market using 'XBTUSD'. The reason for this is because the Kraken OpenOrders API
  # call returns orders with asset pair id to identify the market - this is in the 3 letter commonly used name
  # format, and the adapter uses the marketId to filter the returned orders.
  - id: XRPEUR
    name: XRP/EUR(trailing)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-trailing-stop-strategy
  - id: XRPEUR
    name: XRP/EUR(ta4j-ema)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ema-ta4j-strategy
  - id: XRPEUR
    name: XRP/EUR(ta4j-hidden-divergence)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    marginTradingEnabled: true
    tradingStrategyId: intelligent-hidden-divergence-ta4j-strategy
  - id: XRPEUR
    name: XRP/EUR(trailing-ta4j)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  - id: XRPEUR
    name: XRP/EUR(keltner-trailing-ta4j)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-keltner-ta4j-trailing-stop-strategy
  - id: XRPEUR
    name: XRP/EUR(ta4j-ichimoku)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: BTCEUR
    name: BTC/EUR(trailing-ta4j)
    baseCurrency: XXBT
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  - id: XTZEUR
    name: XTZ/EUR(trailing-ta4j)
    baseCurrency: XXTZ
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  - id: GRTEUR
    name: GRT/EUR(trailing-ta4j)
    baseCurrency: GRT
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  - id: FILEUR
    name: FIL/EUR(trailing-ta4j)
    baseCurrency: FIL
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  - id: ETHEUR
    name: ETH/EUR(trailing-ta4j)
    baseCurrency: XETH
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy
  ###### Ichimoku from here #######
  - id: ADAEUR
    name: ADA/EUR(ta4j-ichimoku)
    baseCurrency: ADA
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: XDGEUR
    name: XDG/EUR(ta4j-ichimoku)
    baseCurrency: XXDG
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: false
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: LTCEUR
    name: LTC/EUR(ta4j-ichimoku)
    baseCurrency: XLTC
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: BCHEUR
    name: BCH/EUR(ta4j-ichimoku)
    baseCurrency: BCH
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: DOTEUR
    name: DOT/EUR(ta4j-ichimoku)
    baseCurrency: DOT
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: XMREUR
    name: XMR/EUR(ta4j-ichimoku)
    baseCurrency: XXMR
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: UNIEUR
    name: UNI/EUR(ta4j-ichimoku)
    baseCurrency: UNI
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: false
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: DASHEUR
    name: DASH/EUR(ta4j-ichimoku)
    baseCurrency: DASH
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: KSMEUR
    name: KSM/EUR(ta4j-ichimoku)
    baseCurrency: KSM
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: false
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: EOSEUR
    name: EOS/EUR(ta4j-ichimoku)
    baseCurrency: EOS
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: XLMEUR
    name: XLM/EUR(ta4j-ichimoku)
    baseCurrency: XXLM
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy
  - id: LINKEUR
    name: LINK/EUR(ta4j-ichimoku)
    baseCurrency: LINK
    counterCurrency: ZEUR
    enabled: true
    marginTradingEnabled: true
    tradingStrategyId: intelligent-ichimoku-ta4j-with-trailing-strategy