############################################################################################
# Market YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# NOTE: XXBT is the same currency code as BTC for Bitcoin on Kraken exchange.
############################################################################################
---
markets:
  # The id value is the market id as defined on the exchange, e.g. 'XBTUSD'.
  # Kraken markets assets (e.g. currencies) can be referenced using their ISO4217-A3 names in the case of ISO
  # registered names, their 3 letter commonly used names in the case of unregistered names,
  # or their X-ISO4217-A3 code (see http://www.ifex-project.org/).
  #
  # The Kraken Exchange Adapter expects the market id to use the 3 letter commonly used names,
  # e.g. you access the XBT/USD market using 'XBTUSD'. The reason for this is because the Kraken OpenOrders API
  # call returns orders with asset pair id to identify the market - this is in the 3 letter commonly used name
  # format, and the adapter uses the marketId to filter the returned orders.
  - id: XRPEUR
    name: XRP/EUR(trailing)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-trailing-stop-strategy
  - id: XRPEUR
    name: XRP/EUR(ta4j)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: intelligent-ta4j-strategy
  - id: XRPEUR
    name: XRP/EUR(trailing-ta4j)
    baseCurrency: XXRP
    counterCurrency: ZEUR
    enabled: true
    tradingStrategyId: intelligent-ta4j-trailing-stop-strategy