############################################################################################
# Trading Strategy YAML config.
#
# - You configure the loading of your strategy using either a className or a beanName field.
# - All fields are mandatory unless stated otherwise.
# - Multiple strategy blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# See the README "How do I write my own Trading Strategy?" section for full details.
############################################################################################
---
strategies:

  - id: intelligent-trailing-stop-strategy

    name: Intelligent Trailing Stop Strategy

    description: >
      Trails a stop order and changes the limits dynamically/intelligently according to the last order (positive --> higher limit, negative --> lower limit)

    beanName: intelligentTrailingStopStrategy

    configItems:
      percentage-of-counter-currency-balance-to-use: 50
      configured-emergency-stop-balance: 50

      sell-stop-limit-percentage-below-break-even: 1.5
      sell-stop-limit-percentage-above-break-even: 0.7
      sell-stop-limit-percentage-minimum-above-break-even: 0.3

      initial-percentage-gain-needed-to-place-buy-order: 0.5
      lowest-price-lookback-count: 80
      times-above-lowest-price-needed: 20

      show-live-chart: true

      persist-ticker-data: false
  - id: intelligent-ema-ta4j-strategy

    name: Intelligent EMA TA4J Strategy

    description: >
      Uses ta4j ema indicataors for entering and leaving the market

    beanName: intelligentEmaTa4jStrategy

    configItems:
      percentage-of-counter-currency-balance-to-use: 50
      configured-emergency-stop-balance: 50

      sell-stop-limit-percentage-below-break-even: 0
      sell-stop-limit-percentage-above-break-even: 0
      sell-stop-limit-percentage-minimum-above-break-even: 0

      show-live-chart: true

      persist-ticker-data: true
  - id: intelligent-ichimoku-ta4j-strategy

    name: Intelligent Ichimoku TA4J Strategy

    description: >
      Uses Ichimoku for entering and fixed stop loss + take profit limits for leaving the market

    beanName: intelligentIchimokuTa4jStrategy

    configItems:
      percentage-of-counter-currency-balance-to-use: 50
      configured-emergency-stop-balance: 50

      sell-stop-limit-percentage-below-break-even: 0
      sell-stop-limit-percentage-above-break-even: 0
      sell-stop-limit-percentage-minimum-above-break-even: 0

      show-live-chart: true

      persist-ticker-data: true
  - id: intelligent-ta4j-trailing-stop-strategy

    name: Intelligent Trailing Stop Strategy (Ta4j Version)

    description: >
      Trails a stop order and changes the limits dynamically/intelligently according to the last order (positive --> higher limit, negative --> lower limit).
      Uses Ta4j for the computations

    beanName: intelligentTa4jTrailingStopStrategy

    configItems:
      percentage-of-counter-currency-balance-to-use: 25
      configured-emergency-stop-balance: 50

      sell-stop-limit-percentage-below-break-even: 7
      sell-stop-limit-percentage-above-break-even: 2
      sell-stop-limit-percentage-minimum-above-break-even: 1

      initial-percentage-gain-needed-to-place-buy-order: 2
      lowest-price-lookback-count: 120
      times-above-lowest-price-needed: 20

      show-live-chart: true

      persist-ticker-data: true